name: 'Hello World'
description: 'Login to dockerhub'
inputs:
  dockerhub-password:  # id of input
    description: 'dockerhub-password'
    required: true
    default: ${{ secrets.DOCKERHUB_PASSWORD }}
#outputs:
#  time: # id of output
#    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'dist/index.js'

